#! /bin/sh

# xrandr
# xrandr --output DP-4 --mode 1920x1080 --rate 165

pipewire &
# pipewire-pulse &
# wireplumber &

# music shit
playerctld daemon

# wallpaper
# feh --no-fehbg --bg-fill .config/bspwm/backgrounds/space.jpg
feh --no-fehbg --bg-fill .config/bspwm/backgrounds/Flag_of_Soviet_Brazil_MultiMonitor.png --no-xinerama # multimonitor wallpaper
#bash ~/.config/bspwm/wallpaper.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           0
bspc config split_ratio          0.50

bspc config focused_border_color "#ca9ee6"
bspc config normal_border_color "#575268"
bspc config active_border_color "#F5E0DC"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config single_monocle        false

# fix pointer
xsetroot -cursor_name left_ptr

# floating windows
#declare -a floats=(Alafloat Lxappearance Arandr \
#Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
#for i in ${floats[@]}; do
#  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
pkill picom
pkill sxhkd
pkill dunst
pkill nm-applet
pkill ksuperkey
pkill xfce4-power-manager

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Mouse wheel speed for my browser
imwheel

# polkit agent
#if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
#    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#fi
/usr/libexec/polkit-gnome-authentication-agent-1 &

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Launch NetworkManager applet
nm-applet &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

# Java applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

# gnome-keyring
gnome-keyring-daemon -s & xdo raise -N Polybar


# polybar
$HOME/.config/bspwm/polybar/launch.sh

setxkbmap br

xhost + local:

export $(dbus-launch)
eval `dbus-launch --auto-syntax`

# live wallpaper
#bash /home/rex/.config/bspwm/wallpaper.sh

# Fix cursor
xsetroot -cursor_name left_ptr

# Polkit
rofi-polkit-agent --theme ~/.config/rofi/catppuccin.rasi

ksuperkey

$HOME/.config/bspwm/mic-volume.sh & disown
